 # Copyright 2020 Crown Copyright
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #
apiVersion: v2
appVersion: 1.0
description: A Helm chart for the Palisade Service layer
name: Palisade-services
version: 0.5.0
dependencies:
  - name: traefik
    version: 0.5.0
    repository: file://charts/traefik
    condition: traefik.install
  - name: dashboard
    version: 0.5.0
    repository: file://charts/dashboard
    condition: dashboard.install
  - name: metrics-server
    version: 0.5.0
    repository: file://charts/metrics-server
    condition: metrics-server.install
  - name: kafka
    version: 0.5.0
    repository: file://charts/kafka
    condition: global.kafka.install
  - name: create-kafka-queues
    version: 0.5.0
    repository: file://charts/create-kafka-queues
    condition: global.kafka.install
  - name: redis
    version: 0.5.0
    repository: file://charts/redis
    condition: global.redis.install
    import-values:
    - child: master
      parent: global.redis.master
    - child: exports
      parent: global.redis.exports
  - name: redis-cluster
    version: 0.5.0
    repository: file://charts/redis-cluster
    condition: global.redis-cluster.install
    import-values:
    - child: cluster
      parent: global.redis-cluster.cluster
    - child: exports
      parent: global.redis-cluster.exports
    - child: service
      parent: global.redis-cluster.service
