apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker-cmds
    image: 779921734503.dkr.ecr.eu-west-1.amazonaws.com/jnlp-did:INFRA
    command:
    - sleep
    args:
    - 99d
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2375

  - name: docker-daemon
    image: docker:19.03.1-dind
    securityContext:
      privileged: true
    resources:
      requests:
        cpu: 20m
        memory: 512Mi
    volumeMounts:
    - name: docker-graph-storage
      mountPath: /var/lib/docker
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""

  - name: maven
    image: 779921734503.dkr.ecr.eu-west-1.amazonaws.com/docker-jnlp-slave-image:INFRA
    command: ['cat']
  tty: true
  env:
  - name: TILLER_NAMESPACE
    value: tiller
  - name: HELM_HOST
    value: :44134
  volumeMounts:
  - mountPath: /var/run
    name: docker-sock
  volumes:
  - name: docker-graph-storage
    emptyDir: {}
  - name: docker-sock
    hostPath:
      path: /var/run
