# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Copied from: https://github.com/bitnami/charts/tree/780db91641bf4e1f98c6e020e1fd971e4d2abc90/bitnami/redis-cluster

{{ if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "redis-cluster.fullname" . }}-metrics
  labels: {{- include "redis-cluster.labels" . | nindent 4 }}
    {{- if .Values.metrics.service.labels }}
    {{ include "common.tplvalues.render" ( dict "value" .Values.metrics.service.labels "context" $ ) | indent 4 }}
    {{- end }}
    app.kubernetes.io/component: "metrics"
  {{- if .Values.metrics.service.annotations }}
  annotations: {{ include "common.tplvalues.render" ( dict "value" .Values.metrics.service.annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  {{- if and (eq .Values.metrics.service.type "LoadBalancer") .Values.metrics.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.metrics.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: metrics
      port: 9121
      targetPort: http-metrics
  selector: {{- include "redis-cluster.matchLabels" $ | nindent 4 }}
{{- end }}
