# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Copied from: https://github.com/helm/charts/blob/6c85be7b88748171afd17affe8b1b57c66bf66a2/incubator/kafka/templates/servicemonitors.yaml

{{ if and .Values.prometheus.jmx.enabled .Values.prometheus.operator.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kafka.fullname" . }}
  namespace: {{ include "palisade.namespace" . }}
  labels:
  {{- include "kafka.monitor.labels" . | nindent 4 }}
  {{- toYaml .Values.prometheus.operator.serviceMonitor.selector | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "kafka.broker.matchLabels" . | nindent 6 }}
  endpoints:
  - port: jmx-exporter
    interval: {{ .Values.prometheus.jmx.interval }}
  {{- if .Values.prometheus.jmx.scrapeTimeout }}
    scrapeTimeout: {{ .Values.prometheus.jmx.scrapeTimeout }}
  {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{ end }}
---
{{ if and .Values.prometheus.kafka.enabled .Values.prometheus.operator.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kafka.fullname" . }}-exporter
  namespace: {{ include "serviceMonitor.namespace" . }}
  labels:
  {{- include "kafka.monitor.labels" . | nindent 4 }}
  {{ toYaml .Values.prometheus.operator.serviceMonitor.selector | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "kafka.monitor.matchLabels" . | nindent 6 }}
  endpoints:
  - port: kafka-exporter
    interval: {{ .Values.prometheus.kafka.interval }}
  {{- if .Values.prometheus.kafka.scrapeTimeout }}
    scrapeTimeout: {{ .Values.prometheus.kafka.scrapeTimeout }}
  {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{ end }}
