# Copyright 2018-2021 Crown Copyright
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "attribute-masking-service.name" . }}
  namespace: {{ include "palisade.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "attribute-masking-service.name" . }}
    helm.sh/chart: {{ include "attribute-masking-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "attribute-masking-service.name" . }}-headless
  podManagementPolicy: "Parallel"
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "attribute-masking-service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "attribute-masking-service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ include "attribute-masking-service.image.name" . }}
        command:
        - bash
        - "-c"
        - |
          [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
          ordinal=${BASH_REMATCH[1]}
          java -jar /usr/share/attribute-masking-service/attribute-masking-service.jar \
          {{ if gt .Values.replicaCount 1.0 }}--akka.kafka.consumer.topics.input-topic.assignment=$ordinal {{ end }} \
            --akka.kafka.consumer.kafka-clients.group.id={{ include "attribute-masking-service.name" . }}-$ordinal
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: web
            containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 90
          failureThreshold: 3
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 90
          failureThreshold: 3
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: "LOADER_PATH"
          value: {{ include "attribute-masking-service.deployment.path" . }}
        - name: "SPRING_CONFIG_ADDITIONAL_LOCATION"
          value: {{ include "attribute-masking-service.config.path" . }}
        {{- $envVars := pluck .Values.global.deployment .Values.global.env | first | default .Values.global.env._default }}
        {{- range $item := $envVars }}
        - name: {{ $item.name }}
          value: {{ $item.value }}
        {{- end }}
        volumeMounts:
        - name: {{ include "attribute-masking-service.classpathJars.name" . }}
          mountPath: {{ include "attribute-masking-service.classpathJars.mount" . }}
        - name: config-volume
          mountPath: {{ include "attribute-masking-service.config.path" . }}
      volumes:
      - name: {{ include "attribute-masking-service.classpathJars.name" . }}
        persistentVolumeClaim:
          claimName: {{ include "attribute-masking-service.classpathJars.name" . }}
          readOnly: true
      - name: config-volume
        configMap:
          name: {{ include "attribute-masking-service.name" . }}-configmap
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
