/*
 * Copyright 2020 Crown Copyright
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package uk.gov.gchq.palisade.service.resource.request;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.springframework.util.Assert;

import uk.gov.gchq.palisade.Generated;

import java.util.Objects;
import java.util.StringJoiner;

/**
 * Contains the information for a request where the User has been identified in the system.
 * Note there are two class that represents the same data where each has a different purpose.
 * uk.gov.gchq.palisade.service.user.response.UserResponse is the output of the User Service
 * uk.gov.gchq.palisade.service.resource.request.ResourceRequest is the input of the Resource Service
 * Generated by the UserService and sent to the ResourceService
 */
@JsonDeserialize(builder = ResourceRequest.Builder.class)
public final class ResourceRequest {

    private final String token; // Unique identifier for this specific request end-to-end
    private final String userJson;  //JSon string for the User object
    private final String resourceId;  //Resource that that is being asked to access
    private final String contextJson;  // represents the context information as a Json string of a Map<String, String>

    private ResourceRequest(final  String token, final String userJson, final String resourceId, final String contextJson) {
        this.token = token;
        this.userJson = userJson;
        this.resourceId = resourceId;
        this.contextJson = contextJson;
    }

    @Generated
    public String getToken() {
        return token;
    }

    @Generated
    public String getUserJson() {
        return userJson;
    }

    @Generated
    public String getResourceId() {
        return resourceId;
    }

    @Generated
    public String getContextJson() {
        return contextJson;
    }


    @Override
    @Generated
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof ResourceRequest)) {
            return false;
        }
        ResourceRequest that = (ResourceRequest) o;
        return token.equals(that.token) &&
                userJson.equals(that.userJson) &&
                resourceId.equals(that.resourceId) &&
                contextJson.equals(that.contextJson);
    }

    @Override
    @Generated
    public int hashCode() {
        return Objects.hash(token, userJson, resourceId, contextJson);
    }

    @Override
    @Generated
    public String toString() {
        return new StringJoiner(", ", ResourceRequest.class.getSimpleName() + "[", "]")
                .add("token='" + token + "'")
                .add("userJson='" + userJson + "'")
                .add("resourceId='" + resourceId + "'")
                .add("contextJson='" + contextJson + "'")
                .add(super.toString())
                .toString();
    }

    /**
     * Builder class for the creation of instances of the UserResponse.  The variant of the Builder Pattern is
     * meant to be used by first populating the Builder class and then us this to create the UserRequest class.
     */
    @JsonPOJOBuilder
    public static class Builder {
        private String token;
        private String userJson;
        private String resourceId;
        private String contextJson;


        public Builder() {
        }

        public Builder token(final String token) {
            this.token = token;
            return this;
        }

        public Builder userJson(final String userJson) {
            this.userJson = userJson;
            return this;
        }

        public Builder resourceId(final String resourceId) {
            this.resourceId = resourceId;
            return this;
        }

        public Builder context(final String contextJson) {
            this.contextJson = contextJson;
            return this;
        }

        public ResourceRequest build() {
            Assert.notNull(token, "Token Id cannot be null");
            Assert.notNull(userJson, "User cannot be null");
            Assert.notNull(resourceId, "Resource Id cannot be null");
            Assert.notNull(contextJson, "Context  cannot be null");
            return new ResourceRequest(token, userJson, resourceId, contextJson);
        }
    }
}

