replicaCount: 1

service:
  port: 80

image:
  repository: palisade/@artifactId@
  tag: @git.commit.id.abbrev@-@revision@
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 750m
    memory: 2.5Gi
  requests:
    cpu: 250m
    memory: 1Gi

nodeSelector: {}
tolerations: []
affinity: {}