# Copyright 2019 Crown Copyright
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: traefik
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/part-of: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
      app.kubernetes.io/part-of: traefik
  template:
    metadata:
      labels:
        app.kubernetes.io/name: traefik
        app.kubernetes.io/part-of: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
      - name: traefik
        image: traefik:v2.0
        args:
        {{- range .Values.container.args }}
        - {{ . }}
        {{- end }}
        ports:
        - name: web
          containerPort: 80
        - name: admin
          containerPort: {{ .Values.admin.port }}
        - name: tls
          containerPort: 443
        livenessProbe:
          httpGet:
            port: {{ .Values.admin.port }}
            path: /ping
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            port: {{ .Values.admin.port }}
            path: /ping
          initialDelaySeconds: 20
          periodSeconds: 10
        securityContext:
          capabilities:
            add:
              - NET_BIND_SERVICE
            drop:
              - ALL
