spring:
  application:
    name: discovery-service

server:
  port: 8761

# Turn off Eureka peer discovery for standalone server
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics