spring:
  application:
    name: palisade-service
  output:
    ansi:
      enabled: always

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
    default-config: default
    audit-service:
      url: http://audit-service:8080