{{- if and .Values.global.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ (index .Values.global.persistence.storageTierName 0) | quote }}
  labels:
    "app.kubernetes.io/name": {{ (index .Values.global.persistence.storageTierName 0) | quote }}
    "helm.sh/chart": "{{ .Chart.Name }}-{{ .Chart.Version }}"
    "app.kubernetes.io/managed-by": "{{ .Release.Service }}"
    "app.kubernetes.io/instance": "{{ .Release.Name }}"
    "app.kubernetes.io/component": {{ (index .Values.global.persistence.storageTierName 0) | quote }}
spec:
  storageClassName: {{ .Values.global.persistence.storageClass | default "" | quote }}
  {{- if .Values.global.localMount.enabled }}
  accessModes:
    {{- range .Values.global.persistence.accessMode }}
  - {{ . | quote }}
    {{- end }}
  {{ else }}
  accessModes:
  - ReadWriteMany
  storageClassName: efs-sc
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.global.persistence.pvcSizes.policy.size }}
  selector:
    matchLabels:
      storage-tier: {{ (index .Values.global.persistence.storageTierName 0) | quote }}
  {{- end }}
