apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-persistent-volume
  namespace: {{ include "palisade.namespace" . }}
  labels:
    type: amazonEBS
    storageTier: "data_service_selector"
    for-app: {{ include "palisade.namespace" . }}
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  accessModes:
  - ReadOnlyMany
  storageClassName: efs-sc
  {{- if eq .Values.hosting "local" }}
  hostPath:
    path: {{ .Values.global.local.path }}
    type: DirectoryOrCreate
  {{- else if eq .Values.hosting "cloud" }}
  {{- if eq .Values.cloudProvider "aws" }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.global.cloud.aws.efsVolumeHandle  }}
    volumeAttributes:
      path: {{ .Values.global.cloud.aws.path }}
  {{- end }}
  {{- else if eq .Values.hosting "metal" }}
  # TODO: what to do for storage on bare-metal deployment
  {{- end }}
