# Copyright 2020 Crown Copyright
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

  {{- if .Values.global.persistence.storageClassDeploy }}
  {{- if .Values.redis.install }}
  {{/* Local Storage classes */}}
  {{- if eq .Values.hosting "local" }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.global.persistence.redisSlave.name }}-{{ include "palisade.namespace" . }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
  {{- end }}
  {{/* AWS Storage classes */}}
  {{- if eq .Values.hosting "aws" }}
  {{- if eq .Values.global.persistence.redisSlave.storageClassName.aws "efs-sc" }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.global.persistence.redisSlave.name }}-{{ .Release.Namespace }}
provisioner: efs.csi.aws.com
  {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}