# Copyright 2018-2021 Crown Copyright
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Create a service that will uses a pod selector to determine on which pod(s) is to be used
# for the zookeeper service.
#
# The palisade application will point to this kafka service which will find a pod that matches the specified service label.
#
apiVersion: v1
kind: Service
metadata:
  name: palisade-zookeeper-proxy
  namespace: {{ include "palisade.namespace" . }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ExternalName
  # Specify the FQDN of the service to use. Pod selectors can't select outside of namespace
  # Docs suggest FQDN can be shortened inside current namespace, and inside current cluster, but this doesn't work in AWS
  {{- if .Values.global.kafka.install }}
  externalName: palisade-zookeeper.{{ include "palisade.namespace" . }}.svc.cluster.local
  {{- else if eq .Values.global.hosting "aws" }}
  externalName: zookeeper.palisade-shared.svc.cluster.local
  {{- end }}
