package uk.gov.gchq.palisade.service.user.requestResponse;


import uk.gov.gchq.palisade.service.user.requestResponse.common.domain.User;

import java.util.Map;



    /**
     * Contains the information for a request where the User has been identified in the system.  This will only be created if the user does exists.
     * Note there are two classes of the same type
     * uk.gov.gchq.palisade.service.resource.request.UserRequestResponse
     * uk.gov.gchq.palisade.service.user.requestResponse.UserRequestResponse
     * Generated by the UserService and sent to the ResourceService
     */
    public class UserRequestResponse {

        private String token; // unique identifier for this specific request end-to-end.  Was a RequestId object now a String.
        // RequestId  represents the  Token shown in the diagram Logical view of Palisade.
        // This information will also be in the header.  This might be removed later if not required in services.
        //the concept of a unique identifier for each transaction is to pulled from the header

        private User user;  //User replaces the user id from the original request.  This is also an indication that the User is in the system.
        private String resourceID;  //the resource that that is being asked to access
        private Map<String, String> context;    // relevant  information about the request.  Was a Context object now a Map.
    }