# Copyright 2020 Crown Copyright
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# The manager creates a number of commands to execute for each service in manager.services
# All fields are *technically* optional but some (classpath, launcher, main) are probably required to start the spawned JVM process
# Extensive use is made of the eureka discovery client to discover services and endpoints - subsequently the "eureka" profile is enabled by default for all services
# Extract the project version (x.y.z-REVISION etc.)
app:
  version: '@project.version@'

eureka:
  client:
    enabled: true

manager:
  # Defaults used internally to the yaml ONLY - these are not interpreted by any java application, just to minimise duplication of long filepaths etc.
  default:
    # Library includes relative to manager.root above (e.g. ../palisade-examples => palisade-services/../palisade-examples)
    # While the example library happens to be the same version as services, it should be declared here as a static name
    library: ../palisade-examples/example-library/target/

  services:

    audit-service:
      jar: audit-service/target/audit-service-${app.version}-exec.jar
      paths:
        - ${manager.default.library}
      profiles:
        - eureka
      log: audit-service-example.log
      err: audit-service-example.err

    data-service:
      jar: data-service/target/data-service-${app.version}-exec.jar
      paths:
        - ${manager.default.library}
      profiles:
        - eureka
      log: data-service-example.log
      err: data-service-example.err

    palisade-service:
      jar: palisade-service/target/palisade-service-${app.version}-exec.jar
      paths:
        - ${manager.default.library}
      profiles:
        - eureka
      log: palisade-service-example.log
      err: palisade-service-example.err

    policy-service:
      jar: policy-service/target/policy-service-${app.version}-exec.jar
      paths:
        - ${manager.default.library}
      profiles:
        - eureka
      log: policy-service-example.log
      err: policy-service-example.err

    resource-service:
      jar: resource-service/target/resource-service-${app.version}-exec.jar
      profiles:
        - eureka
      log: resource-service.log
      err: resource-service.err

    user-service:
      jar: user-service/target/user-service-${app.version}-exec.jar
      paths:
        - ${manager.default.library}
      profiles:
        - example
      log: user-service-example.log
      err: user-service-example.err
